model:
  lr: 0.0002
  lambda_cyc: 10

data:
  root: ./data/monet2photo
  size: 256
  batch_size: 1

trainer:
  max_epochs: 200
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args: {monitor: val/fid, patience: 5}
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args: {save_dir: logs, name: cg}
