model:
    G:
      class_path: cg.models.Generator
    F:
      class_path: cg.models.Generator
    Dx:
      class_path: cg.models.Discriminator
    Dy:
      class_path: cg.models.Discriminator

data:
  root: data/monet2photo
  size: 256
  batch_size: 1

fit:
    trainer:
        max_epochs: 200
        accelerator: gpu
        devices: 1
        precision: 16-mixed
        callbacks:
          - class_path: lightning.pytorch.callbacks.EarlyStopping
            init_args: {monitor: val/fid, patience: 5}
        logger:
          class_path: lightning.pytorch.loggers.TensorBoardLogger
          init_args: {save_dir: logs, name: cg}
