ckpt_path: logs/cg_vangogh/version_3/checkpoints/last.ckpt
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args: { save_dir: logs, name: predict }

  accelerator: gpu
  devices: 1
  precision: 16-mixed
  callbacks:
    - class_path: cg.callbacks.video_writer.VideoWriterCallback
      init_args: { out_path: results/videos/church1.mp4, fps: 30.0, size: [640, 360], codec: "mp4v" } # 结果输出的路径，同时先用src/cg/utils/vidinfo.py查看视频信息，设置size和fps
model:
  G:
    class_path: cg.models.Generator.Generator
  F:
    class_path: cg.models.Generator.Generator
  Dx:
    class_path: cg.models.Discriminator.Discriminator
  Dy:
    class_path: cg.models.Discriminator.Discriminator

data:
  class_path: cg.data.video.VideoDM
  init_args:
    path: data/videos/church1.mp4 # 读取需要处理的视频的路径
    batch_frames: 16
    num_workers: 0




